/**
 * The credits the game shows, generated by `node scripts/credits.mjs` from the build’s records.
 *
 * Do not edit: `npm run check:credits` regenerates it and fails the gate on a difference. The
 * source of truth is the recipes in `scripts/weapon-build.mjs` and `MIXAMO` in that script.
 */

/** One source, as a player reads it: what it is, who made it, and the licence it comes under. */
export interface CreditEntry {
  readonly title: string;
  readonly author: string;
  readonly license: string;
  /** The licence deed. CC-BY asks for the link, not only the name. */
  readonly licenseUrl: string;
  /** The model’s page: the "material" CC-BY asks to be linked. */
  readonly url: string;
  /** What the game draws from it, in the names the player sees. */
  readonly used: string;
}

/** The Sketchfab models: weapons, attachments, the knife and the first-person hands. */
export const MODEL_CREDITS: readonly CreditEntry[] = [
  {
    title: '[FREE - Modular] L1A1 SLR',
    author: 'Aperture Aerospace',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
    url: 'https://sketchfab.com/3d-models/free-modular-l1a1-slr-d63c3e0d97464bc5b2a58cadf35e52f5',
    used: 'LONGBOW',
  },
  {
    title: 'AK-74 Pack (game asset)',
    author: 'Armored Wave',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
    url: 'https://sketchfab.com/3d-models/ak-74-pack-game-asset-29978f495f824173b44a3ba40cb8ebd8',
    used: 'VULCAN, OPTIC',
  },
  {
    title: 'Beretta M9',
    author: 'eNse7en',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
    url: 'https://sketchfab.com/3d-models/beretta-m9-348015284eca46fe8e1822508381dfd8',
    used: 'TALON',
  },
  {
    title: 'C4 - Sticky Bomb',
    author: 'Astate',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
    url: 'https://sketchfab.com/3d-models/c4-sticky-bomb-33ca0341ff334d1f89f9f5ff4213297c',
    used: 'SEMTEX',
  },
  {
    title: 'Claymore Mine',
    author: 'MustafaYerebasmaz',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
    url: 'https://sketchfab.com/3d-models/claymore-mine-486238027ee340f68fb4c4c973734458',
    used: 'CLAYMORE',
  },
  {
    title: 'Flashbang grenade',
    author: 'Nikolay Kudrin',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
    url: 'https://sketchfab.com/3d-models/flashbang-grenade-2799b0b859c74db6ae8752fdc6bb4c04',
    used: 'FLASHBANG',
  },
  {
    title: 'Free - M4 Modular Kit Gun',
    author: 'Karnaval',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
    url: 'https://sketchfab.com/3d-models/free-m4-modular-kit-gun-1665416c071747bb9c20aa652849b579',
    used: 'CARBINE, SUPPRESSOR, GRIP',
  },
  {
    title: 'Free Modular MP5 Kit',
    author: 'Karnaval',
    license: 'SKETCHFAB Standard',
    licenseUrl: 'https://sketchfab.com/licenses',
    url: 'https://sketchfab.com/3d-models/free-modular-mp5-kit-d381a0438a8b45c2bac6f59120fbb52f',
    used: 'WASP',
  },
  {
    title: 'Hand With Gloves',
    author: 'JUST',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
    url: 'https://sketchfab.com/3d-models/hand-with-gloves-5a6a434b8ec943ffacc581358781eecb',
    used: 'HANDS',
  },
  {
    title: 'L115A3',
    author: 'Mortavex',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
    url: 'https://sketchfab.com/3d-models/l115a3-3b732b97c72440229c17b78e565f965e',
    used: 'KESTREL',
  },
  {
    title: 'M150 Sniper Rifle (Game Ready)',
    author: 'Bl4ckGh0st',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
    url: 'https://sketchfab.com/3d-models/m150-sniper-rifle-game-ready-0f71498f1f694b30be77c9779361c6cc',
    used: 'VANTAGE',
  },
  {
    title: 'M18 Smoke Grenade',
    author: 'Vanillatography',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
    url: 'https://sketchfab.com/3d-models/m18-smoke-grenade-46343925ad0e47cf927e66da7953c372',
    used: 'SMOKE',
  },
  {
    title: 'M26 Grenade',
    author: 'mapleaber',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
    url: 'https://sketchfab.com/3d-models/m26-grenade-a623558f347f4e1197f7a5552f199e68',
    used: 'FRAG',
  },
  {
    title: 'Modular P90 Tactical',
    author: 'doomsentinel',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
    url: 'https://sketchfab.com/3d-models/modular-p90-tactical-080897fc0366455884b1a916684313fe',
    used: 'MERIDIAN',
  },
  {
    title: 'MTech USA Xtreme Tactical Knife Low-poly',
    author: 'xivxiy',
    license: 'SKETCHFAB Standard',
    licenseUrl: 'https://sketchfab.com/licenses',
    url: 'https://sketchfab.com/3d-models/mtech-usa-xtreme-tactical-knife-low-poly-789da4919af740479eb8dc7c4901ae89',
    used: 'KNIFE',
  },
  {
    title: 'Rifle Laser Sight',
    author: 'trolosqlfod',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
    url: 'https://sketchfab.com/3d-models/rifle-laser-sight-55d74d7d4f6a4071af856d2ffc2c429a',
    used: 'LASER',
  },
  {
    title: 'Spas 12',
    author: 'Luiz Bueno',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
    url: 'https://sketchfab.com/3d-models/spas-12-614140daf5e4467fa0e36b6c23d70621',
    used: 'BREACHER',
  },
  {
    title: 'TAR - 21 (Tavor). Black and White.',
    author: 'Nik Vega',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
    url: 'https://sketchfab.com/3d-models/tar-21-tavor-black-and-white-40dc15941e0b456692c83a97bfcd2474',
    used: 'HALCYON',
  },
];

/** Mixamo: every character skin and every animation clip. Attribution is not required for it. */
export const CHARACTER_CREDIT: CreditEntry = {
  title: 'Mixamo characters and animations',
  author: 'Adobe (Mixamo)',
  license: 'Mixamo Terms of Use',
  licenseUrl: 'https://helpx.adobe.com/creative-cloud/faq/mixamo-faq.html',
  url: 'https://www.mixamo.com/',
  used: 'CHARACTERS, ANIMATIONS',
};

/** Where the full page is, for the reader who wants every file and every link. */
export const CREDITS_NOTE = 'Full attribution, with every built file and every link: CREDITS.md in the project repository.';
