import * as THREE from 'three';
import type { CamoId } from '../../shared/meta/Camos';
import { buildWeaponModel, type WeaponModel } from '../weapons/WeaponMesh';
import type { WeaponAssetService } from '../weapons/WeaponAssetService';

/**
 * The loadout editor's weapon preview (playtest round 4, F15).
 *
 * *"Make the technical choices visual — you see the weapon you are choosing."* The screen
 * printed twelve names and thirteen numbers and never once showed the object.
 *
 * ## One source for what a weapon looks like
 *
 * The model is `buildWeaponModel` — the viewmodel's own builder, from the same
 * `WeaponModelSpec` the gun in your hands is built from, with the same three shared materials
 * and the same camo textures. There is no second description of a rifle anywhere in this file,
 * which is the whole design constraint: a preview drawn from its own coordinates is a picture
 * that starts out right and drifts the first time a sight height changes. This project has no
 * asset files at all (S2), so "the model" and "the picture of the model" are the same code.
 *
 * The camo comes through the same argument `ClientMatch` passes, so choosing a finish in the
 * Camouflage row repaints the model with it — the camo is generated by `CamoTextures` from a
 * seeded Rng and is byte-identical to the one the match will apply.
 *
 * ## Why it has a renderer of its own
 *
 * `Renderer`'s canvas is full-screen and *behind* the DOM front end, and `.op-screen` paints a
 * near-opaque gradient with a backdrop blur over the whole of it. Rendering the preview into a
 * scissored corner of that canvas would put it behind the screen it belongs to. So this owns a
 * small `WebGLRenderer` on its own canvas, created on first `show()` rather than at boot —
 * most sessions never open the editor, and a context nobody looks at is a context nobody
 * should have allocated.
 *
 * Materials and textures are shared with the main renderer and are cached per *process*
 * (`WeaponMesh.sharedWeaponSurfaces`), which is safe across two contexts: three keeps its per-object
 * GPU state in a map on the renderer, so each uploads its own copy and neither disposes the
 * other's. Nothing releases the caches today; a page teardown, if one is ever built, disposes
 * them in `WeaponMesh`, not per context.
 *
 * ## Lighting
 *
 * The same three-light rig as `ViewmodelLayer`, for the same reason the geometry is shared: a
 * weapon lit differently here reads as a different weapon. Key from above-left-front, a cool
 * rim from behind to hold the silhouette off the panel, and a hemisphere fill so the underside
 * of the receiver is not black.
 */

export interface WeaponPreviewDeps {
  /** The same anisotropy `ClientMatch` builds its viewmodels with. */
  readonly anisotropy: () => number;
  /**
   * The same templates `ClientMatch` builds from (M19), so the picture and the gun agree.
   * Null where a picture is all that is wanted and no file should be fetched for it.
   */
  readonly weaponAssets: WeaponAssetService | null;
  /**
   * Design-frame pixels of the canvas (Create-a-Class round 2, 2026-09-15). The default is
   * the band's 360×200; the editor's stage puts the weapon where the operator stands at
   * 860×480 — the same 1.8 aspect, so the lens and `FIT_DIAGONAL` hold, and the backing
   * store follows the on-screen rect the way `CharacterStage`'s does.
   */
  readonly width?: number;
  readonly height?: number;
  readonly className?: string;
}

/** Pixels. The band's panel; a stage-sized preview passes its own. */
const WIDTH = 360;
const HEIGHT = 200;

/** Degrees per second the model turns on its own. Slow enough to read, fast enough to notice. */
const SPIN_DEG_PER_SEC = 26;

/**
 * Metres the model's bounding diagonal is scaled to.
 *
 * Fitting the *diagonal* rather than a width is what makes one number work for a pistol and a
 * sniper rifle: whatever angle the turntable is at, the projected extent of a box is at most
 * its diagonal, so a diagonal that fits the frame fits it at every angle. The frame is about
 * 0.75 m wide at the camera's distance, so this leaves room and never clips a muzzle mid-spin.
 */
const FIT_DIAGONAL = 0.62;

export class WeaponPreview {
  readonly element: HTMLElement;

  private readonly deps: WeaponPreviewDeps;
  private readonly canvas: HTMLCanvasElement;
  private readonly caption: HTMLElement;
  private readonly scene = new THREE.Scene();
  private readonly camera: THREE.PerspectiveCamera;
  /** The model hangs off this, so the spin is one rotation rather than per-part maths. */
  private readonly turntable = new THREE.Group();

  /** Built on first `show`. See the file comment. */
  private renderer: THREE.WebGLRenderer | null = null;
  private model: WeaponModel | null = null;
  /** What `model` is, so an unchanged selection does not rebuild it every refresh. */
  private modelKey = '';
  private spinRadians = 0;
  private readonly width: number;
  private readonly height: number;
  private lastSeenWidth = 0;
  private lastSeenHeight = 0;

  constructor(deps: WeaponPreviewDeps) {
    this.deps = deps;
    this.width = deps.width ?? WIDTH;
    this.height = deps.height ?? HEIGHT;
    this.camera = new THREE.PerspectiveCamera(30, this.width / this.height, 0.05, 12);

    this.canvas = document.createElement('canvas');
    this.canvas.className = 'lo-preview__canvas';
    this.canvas.width = this.width;
    this.canvas.height = this.height;

    this.caption = document.createElement('div');
    this.caption.className = 'lo-preview__name op-label';

    this.element = document.createElement('div');
    this.element.className = deps.className === undefined ? 'lo-preview' : `lo-preview ${deps.className}`;
    this.element.append(this.canvas, this.caption);

    const key = new THREE.DirectionalLight(0xffffff, 2.6);
    key.position.set(-0.55, 0.85, 0.35);
    const rim = new THREE.DirectionalLight(0x9ec4ff, 1.4);
    rim.position.set(0.95, 0.2, -1.5);
    const fill = new THREE.HemisphereLight(0x9fb0c8, 0x22252b, 1.35);
    this.scene.add(key, key.target, rim, rim.target, fill, this.turntable);

    // Slightly above and in front, looking down the length of the weapon at a three-quarter
    // angle: the pose a shop screen uses, because it shows the profile and the receiver at
    // once. The turntable's spin does the rest.
    this.camera.position.set(0.16, 0.14, 0.78);
    this.camera.lookAt(0, -0.01, 0);
  }

  /**
   * Show a weapon. Cheap to call every refresh: an unchanged (weapon, camo) pair is a no-op.
   */
  show(weaponId: string, camo: CamoId | null, name: string): void {
    const key = `${weaponId}|${camo ?? ''}`;
    if (key !== this.modelKey) {
      this.modelKey = key;
      this.disposeModel();
      // A picture of the weapon, not of somebody holding it: no gloves.
      const model = buildWeaponModel(weaponId, this.deps.anisotropy(), camo, { hands: false, assets: this.deps.weaponAssets });
      this.upgradeWhenLoaded(model, key, weaponId, camo, name);
      /**
       * Framed by its own size rather than by a per-weapon number.
       *
       * The pistol is genuinely a different object from the LMG — `WeaponModelSpec.scale`
       * says so — and a fixed camera distance would draw one as a speck and clip the other.
       * The bounding box comes from the geometry that was just built, so a spec change moves
       * the framing with it and there is no second table to keep in step.
       */
      const bounds = new THREE.Box3().setFromObject(model.root);
      const centre = bounds.getCenter(new THREE.Vector3());
      const span = Math.max(bounds.getSize(new THREE.Vector3()).length(), 0.001);
      const fit = FIT_DIAGONAL / span;
      /**
       * Scale, **then** offset by the *scaled* centre, and the order is not cosmetic.
       *
       * A group's local matrix is `T · R · S`, so the translation is applied outside the
       * scale: a child ends up at `fit · s · c + position`. The box was measured at `s`, so
       * subtracting its raw centre would leave the model off the turntable's axis by
       * `(fit - 1)` times that centre — a weapon that wobbles as it spins rather than turning
       * on the spot, which is subtle enough to look like a modelling choice.
       */
      model.root.scale.multiplyScalar(fit);
      model.root.position.copy(centre).multiplyScalar(-fit);
      this.turntable.add(model.root);
      this.model = model;
    }
    if (this.caption.textContent !== name) this.caption.textContent = name;
  }

  /**
   * The file in place of the primitives once it lands (M19): the same swap `ClientMatch` makes,
   * done by forgetting the key and showing again. A late promise checks the key first — the
   * pointer has usually moved on — and a weapon with no file resolves at once and does nothing.
   */
  private upgradeWhenLoaded(model: WeaponModel, key: string, weaponId: string, camo: CamoId | null, name: string): void {
    const assets = this.deps.weaponAssets;
    if (assets === null || model.source === 'glb' || assets.statusFor(weaponId) === 'none') return;
    void assets.preload(weaponId).then(
      () => {
        if (this.modelKey !== key || this.model !== model) return;
        this.modelKey = '';
        this.show(weaponId, camo, name);
      },
      () => undefined,
    );
  }

  /** One frame. Driven from the render pass — see `LoadoutEditor.tick`. */
  tick(dt: number): void {
    if (this.model === null) return;
    this.spinRadians += SPIN_DEG_PER_SEC * (Math.PI / 180) * dt;
    this.turntable.rotation.y = this.spinRadians;
    const renderer = this.ensureRenderer();
    this.fitBackingStore(renderer);
    renderer.render(this.scene, this.camera);
  }

  /**
   * Drop the model when the screen goes away, and keep the context.
   *
   * The geometry is per model and worth releasing between visits; the renderer is not — the
   * expensive part of it is the context, and re-creating one per visit to a screen the player
   * flips in and out of is how a page runs out of them.
   */
  release(): void {
    this.disposeModel();
    this.modelKey = '';
  }

  dispose(): void {
    this.disposeModel();
    this.renderer?.dispose();
    this.renderer = null;
    this.element.remove();
  }

  private ensureRenderer(): THREE.WebGLRenderer {
    const existing = this.renderer;
    if (existing !== null) return existing;
    const made = new THREE.WebGLRenderer({ canvas: this.canvas, antialias: true, alpha: true });
    // The same colour pipeline as `Renderer`, or the weapon here is a different colour from
    // the weapon in the match. Exposure included: ACES without it is a different curve.
    made.outputColorSpace = THREE.SRGBColorSpace;
    made.toneMapping = THREE.ACESFilmicToneMapping;
    made.toneMappingExposure = 1.25;
    this.renderer = made;
    return made;
  }

  /**
   * Size the backing store to what is on screen: the canvas's CSS box is in frame pixels and
   * the frame is zoomed, so the rect is the truth and the attribute is not (as `CharacterStage`).
   */
  private fitBackingStore(renderer: THREE.WebGLRenderer): void {
    const rect = this.canvas.getBoundingClientRect();
    const ratio = Math.min(2, window.devicePixelRatio || 1);
    const width = Math.max(1, Math.round((rect.width || this.width) * ratio));
    const height = Math.max(1, Math.round((rect.height || this.height) * ratio));
    if (width === this.lastSeenWidth && height === this.lastSeenHeight) return;
    this.lastSeenWidth = width;
    this.lastSeenHeight = height;
    renderer.setSize(width, height, false);
    this.camera.aspect = width / height;
    this.camera.updateProjectionMatrix();
  }

  private disposeModel(): void {
    const model = this.model;
    if (model === null) return;
    this.turntable.remove(model.root);
    // Geometry only. The materials and textures belong to the process — see the file comment.
    model.dispose();
    this.model = null;
  }
}
